### ISSUE TITLE
[Feature request] Allow "merging" of technical replicates in MQ exporter

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/sdrf-pipelines#81]
E.g. I would like to able to construct an mqpar.xml with the following:
```
	<experiments>
		<string>Sample1</string>
		<string>Sample1</string>
		<string>Sample1</string>
		<string>Sample2</string>
		<string>Sample2</string>
		<string>Sample2</string>
...
	</experiments>
```
Instead of the current:
```
	<experiments>
		<string>Sample1_Tr_1</string>
		<string>Sample1_Tr_2</string>
		<string>Sample1_Tr_3</string>
		<string>Sample2_Tr_1</string>
		<string>Sample2_Tr_2</string>
		<string>Sample2_Tr_3</string>
...
	</experiments>
```

Whether this should be the default is debatable I guess.

**Comment by daichengxin** [comment]
Hi jpfeuffer @jpfeuffer , in MaxQuant Tutorial: `experiment: everything that has the same name in the experiment column will be combined in the output – e.g. all slices of one gel lane belong to one experiment (everything that has the same identifier in experiment column will be summarized at the end), technical replicates belong to different experiments (otherwise, the intensities would be combined)`.  So I used Sample + technical as the experiment id. I am not sure if Allow "merging" of technical replicates  makes sense

**Comment by jpfeuffer** [comment]
Ah, thanks for pointing that out. I did not know that. I thought they might have a clever way of combining them. I will resort to statistical post-processing on the single replicate quantities then.
